name: continuous-integration
on: pull_request
jobs:
  continue-integration:
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v3
    -name: Teste Workflow
    uses: actions/setup-node@v2
    with:
      node-version: 23.
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm run test
      
      